query Homes {
  homes {
    id
    name
    title
    description
    listprices {
      id
      name
      description
      color
      price
      total
      visible
      uid
    }
    image {
      url
    }
    icon
    color
    disabled
    extralist {
      id
      name
      description
      count
      max
      active
      category
      price
    }
  }
}
