query HomePage {
  homePage {
    id
    metatitle
    titletop
    titlemiddle
    description
    metades
    homes {
      id
      name
      title
      description
      listprices {
        id
        name
        description
        color
        price
        visible
        uid
      }
      image {
        url
      }
      modalimg {
        url
      }
      icon
      color
      disabled
      extralist {
        id
        name
        description
        count
        max
        active
        category
        price
      }
    }
  }
}
