query AboutPage($locale: String!) {
  aboutPage(locale: $locale) {
    id
    title
    description
    metatitle
    metades
    metatitle
    image{url}
    avatar{  
      id
      name
      category
      image{url}
    }
  }
}
