query PortfolioPage($locale: String!) {
  portfolioPage(locale: $locale) {
    id
    title
    description
    metatitle
    metades
    portfolios {
      id
      uid
      title
      description
      image {
        url
      }
    }
  }
}
