query Portfolios {
  portfolios {
    id
    description
    items{
      title
      video{url}
      thumbnail{url}
    }
    cards{
      image{url}
      title
      description
      link
    }
    families{
      title
      image{url}
      width
      category
    }
     branding{
      title
      image{url}
      width
      category
    }
    stilling{
      title
      image{url}
      width
      category
    }
  }
}